version: '3.8'

services:
  dynamodb-local:
    image:  amazon/dynamodb-local
    container_name: mazemail-dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      -  ./dynamodb-data:/tmp/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamo-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - dynamodb-local

  shopify:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    image: amplience-dev
    container_name: amplience-shop-extension
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/code
      - /code/.next
      - /code/node_modules
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - dynamodb-local